name: hello-class
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second-step
        run: echo "hello africa"